version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: document-analysis-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/app.db
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SECRET_KEY=${SECRET_KEY:-development_secret_key_change_in_production}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - backend_data:/app/data
      - ./src/app:/app/src/app:ro  # Mount source for development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: document-analysis-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  # Optional: Redis for session storage in production
  redis:
    image: redis:7-alpine
    container_name: document-analysis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - app-network

volumes:
  backend_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
